services:
  vcrnet:
    image: vcrnet5:latest
    restart: always
    environment:
      - TZ=Europe/Berlin
      - OUTERIP=$MYIP
      - OUTERFTP=$FTPPort
    volumes:
      - $CONFIG:/usr/share/jmsdvbnet
      - $RECORDING:/Recordings
    ports:
      - 29300-29399:29300-29399
      - $PORT:8080
      - $FTPPort:8081
