services:
  vcrnet:
    image: vcrnet5:latest
    restart: always
    environment:
      - TZ=Europe/Berlin
      - OUTERIP=$MYIP
      - OUTERFTP=$FTPPort
    volumes:
      - $CONFIG:/usr/share/jmsdvbnet
      - $RECORDING:/Recordings
    ports:
      - 29300-29399:29300-29399
      - $PORT:8080
      - $FTPPort:8081
  nginx:
    image: docker.io/nginx:stable-alpine
    restart: always
    ports:
      - $EXTPORT:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:Z
      - ./passwd:/etc/nginx/basic_auth:Z
      - ./host.crt:/etc/ssl/certs/nginx/host.crt:Z
      - ./host.key:/etc/ssl/certs/nginx/host.key:Z
