services:
  vcrnet:
    image: vcrnet5:latest
    restart: always
    environment:
      - TZ=Europe/Berlin
      - OUTERIP=$MYIP
    volumes:
      - $CONFIG:/usr/share/jmsdvbnet
      - $RECORDING:/Recordings
    ports:
      - 29300:29300
      - 29301:29301
      - 29302:29302
      - 29303:29303
      - 29304:29304
      - $PORT:8080
      - $FTPPORT:8081
