services:
  vcrnet:
    image: vcrnet5:latest
    restart: always
    environment:
      - TZ=Europe/Berlin
    volumes:
      - $CONFIG:/usr/share/jmsdvbnet
      - $RECORDING:/Recordings
    ports:
      - $PORT:8080
      - $FTPPORT:8081
