name: Hello World

on:
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Verify
        env:        
          TEST: ${{ secrets.TEST }}
        run: |
          env
