name: Publish to NuGet

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/master
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION}
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${VERSION} --no-build --output Packed
      - name: Push
        run: |
          dotnet nuget push Packed/JMS.DVB.NET.Algorithms.${VERSION}.nupkg --source https://nuget.pkg.github.com/JMS-1/index.json --api-key ${GITHUB_TOKEN}
          dotnet nuget push Packed/JMS.DVB.NET.CardServer.${VERSION}.nupkg --source https://nuget.pkg.github.com/JMS-1/index.json --api-key ${GITHUB_TOKEN}
          dotnet nuget push Packed/JMS.DVB.NET.CardServerCore.${VERSION}.nupkg --source https://nuget.pkg.github.com/JMS-1/index.json --api-key ${GITHUB_TOKEN}
          dotnet nuget push Packed/JMS.DVB.NET.Common.${VERSION}.nupkg --source https://nuget.pkg.github.com/JMS-1/index.json --api-key ${GITHUB_TOKEN}
          dotnet nuget push Packed/JMS.DVB.NET.DVBNETLegacy.${VERSION}.nupkg --source https://nuget.pkg.github.com/JMS-1/index.json --api-key ${GITHUB_TOKEN}
          dotnet nuget push Packed/JMS.DVB.NET.EPG.${VERSION}.nupkg --source https://nuget.pkg.github.com/JMS-1/index.json --api-key ${GITHUB_TOKEN}
          dotnet nuget push Packed/JMS.DVB.NET.HardwareAbstration.${VERSION}.nupkg --source https://nuget.pkg.github.com/JMS-1/index.json --api-key ${GITHUB_TOKEN}
          dotnet nuget push Packed/JMS.DVB.NET.Recording.${VERSION}.nupkg --source https://nuget.pkg.github.com/JMS-1/index.json --api-key ${GITHUB_TOKEN}
          dotnet nuget push Packed/JMS.DVB.NET.SITables.${VERSION}.nupkg --source https://nuget.pkg.github.com/JMS-1/index.json --api-key ${GITHUB_TOKEN}
          dotnet nuget push Packed/JMS.DVB.NET.SourceManagement.${VERSION}.nupkg --source https://nuget.pkg.github.com/JMS-1/index.json --api-key ${GITHUB_TOKEN}
          dotnet nuget push Packed/JMS.DVB.NET.TS.${VERSION}.nupkg --source https://nuget.pkg.github.com/JMS-1/index.json --api-key ${GITHUB_TOKEN}
          dotnet nuget push Packed/JMS.DVB.NET.Ubuntu.${VERSION}.nupkg --source https://nuget.pkg.github.com/JMS-1/index.json --api-key ${GITHUB_TOKEN}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
